# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-12 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='note_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='note_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='simpleuser',
            old_name='user_login',
            new_name='login',
        ),
        migrations.AddField(
            model_name='note',
            name='tag',
            field=models.CharField(default='other', max_length=20),
        ),
    ]
