# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-15 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20171012_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='status',
            field=models.CharField(choices=[('None', 'none'), ('Normal', 'green'), ('Middle', 'orange'), ('Urgent', 'red')], default='None', max_length=20),
        ),
    ]
