# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-18 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='author',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='notes.SimpleUser'),
        ),
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateTimeField(editable=False, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='note',
            name='status',
            field=models.CharField(choices=[('None', 'none'), ('Low', 'green'), ('Normal', 'orange'), ('Urgent', 'red')], default='None', max_length=20),
        ),
    ]
