# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-03 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20171018_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='status',
            field=models.CharField(choices=[('', 'None'), ('low', 'Low'), ('normal', 'Normal'), ('urgent', 'Urgent')], default='', max_length=20),
        ),
    ]
