# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_auto_20171103_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListOfNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='note',
            name='tag',
            field=models.CharField(default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='simpleuser',
            name='login',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='listofnotes',
            name='author',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='notes.SimpleUser'),
        ),
        migrations.AddField(
            model_name='note',
            name='note_list',
            field=models.ForeignKey(default=None, editable=False, on_delete=django.db.models.deletion.CASCADE, to='notes.ListOfNotes'),
        ),
    ]
