# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_auto_20171109_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='status',
            field=models.CharField(blank=True, choices=[('', ''), ('low', 'Low'), ('normal', 'Normal'), ('urgent', 'Urgent')], default='', max_length=20),
        ),
    ]
