# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_auto_20171225_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='status',
            field=models.CharField(blank=True, choices=[('', ''), ('low', 'Low'), ('normal', 'Normal'), ('urgent', 'Urgent')], max_length=20),
        ),
        migrations.AlterField(
            model_name='note',
            name='tag',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
